### ISSUE TITLE
Account for extra message overhead added by server when splitting

### ISSUE THREAD

**Issue by wjt** [meshy/framewirc#21]
[This](https://github.com/meshy/framewirc/blob/45ba4266419ca7e864defa8971e9fc94389637d2/framewirc/message.py#L76,L78) doesn't take into account the "relay prefix" that the server will add to your messages before forwarding them to their recipients. See [this logic in telepathy-idle](https://cgit.freedesktop.org/telepathy/telepathy-idle/tree/src/idle-connection.c#n1004) for an attempt (hopefully successful, but who knows) to work out what the prefix will be. It depends on what the server believes your Unix username and hostname to be; so the client WHOISes itself to work these out.

**Comment by meshy** [comment]
Thank you for this -- I hope I get the time to look into this soon `:)`
